version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      # - "127.0.0.1:53:53"                # DNS config (required for Pro)
      # - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - DEBUG=1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      # Using host as Lambda DNS via Docker gateway (i.e., host.docker.internal)
      # - LAMBDA_DOCKER_DNS=192.168.65.254
      # Using LocalStack as Lambda DNS
      # - LAMBDA_DOCKER_DNS=192.168.160.2
      # Using host as fallback DNS server via Docker gateway (i.e., host.docker.internal)
      # - DNS_SERVER=192.168.65.254

      # Disable DNS server entirely
      # - DNS_ADDRESS=0
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
